### ISSUE TITLE
Mouse down detection appears to be broken

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/ray.mod#1]
Detecting whether left/right mouse button is down appears to return true for both buttons if either is down.

Perhaps updating to the latest raylib sources will resolve the problem.

**Comment by GWRon** [comment]
Latest commits in raylib fixed this issue.
https://github.com/raysan5/raylib/commit/3a073db0290e004cafaf2fdc6f1dbbfc990ae68e

There was also a bug with key-input
https://github.com/raysan5/raylib/commit/6b8f30964dc9490fb4725a7c4764d793202ee48f
