### ISSUE TITLE
Examples don't build in current releases

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/ray.mod#2]
Hi Brucey,

The ray.mod readme suggests that simply downloading the latest release should work, but it doesn't.

I saw a recent update adding StaticArray as a keyword, so have updated my bcc and bmk (plus pub.mod) -- somehow successfully! -- and they work now.

Just noting in case you want to update the releases for this.

Also, just starting matrices and vectors in the OpenGL tutorial and realised raylib's maths functions should be all I need... and, may the gods bless you, it's already here for me, so thanks for that!

**Comment by woollybah** [comment]
Thanks. I'll get an update out shortly.

There's also BRL.Vector and BRL.Matrix, which should provide similar functionality.

**Comment by DruggedBunny** [comment]
Thanks, Brucey, running the latest now and it's all going well!

I had seen those mods in passing but not properly looked until now... the operator overloads definitely win over raylib's versions!
